#!/bin/sh
SCRIPT="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
DIR=`dirname "${SCRIPT}"}`
exec scala $0 $DIR $SCRIPT "$@"
::!#

import java.io.File
import scala.sys.process._

object App {
  def main(args: Array[String]): Unit = {
    val start:  Int = args(2).toInt
    val finish: Int = args(3).toInt
    val increment: Int = args(4).toInt
    val numRuns = if (args.length >= 6) args(5).toInt
    else 10

    for (len <- (start to finish by increment)) {
      val runBench: String = "scala -Dsize="+ len +" -cp kryo-2.20/jars/production/kryo-2.20.jar:kryo-2.20/jars/production/objenesis-1.2.jar:kryo-2.20/jars/production/reflectasm-1.07.jar:kryo-2.20/jars/production/asm-4.0.jar:kryo-2.20/jars/production/kryo-serializers-0.20.jar:target/scala-2.9.3/classes KryoEvactorBench " + numRuns
      runBench.!
    }
  }
}
